version: '3'

services:
  virtuoso:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8890:8890"  # SPARQL and HTTP
      - "1111:1111"  # SQL port
    environment:
      - ONTOLOGY_FILE=${ONTOLOGY_FILE:-/data/pizza.owl}
    volumes:
      - ./data:/data:ro
      - virtuoso_data:/opt/virtuoso-opensource/database/data
      - virtuoso_logs:/opt/virtuoso-opensource/database/logs
      - virtuoso_ontologies:/opt/virtuoso-opensource/share/ontologies
    restart: unless-stopped

volumes:
  virtuoso_data:
  virtuoso_logs:
  virtuoso_ontologies:
