services:
  virtuoso:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8890:8890"  # SPARQL and HTTP
      - "1111:1111"  # SQL port
    environment:
      - ONTOLOGY_FILE=${ONTOLOGY_FILE}
    volumes:
      - ./data:/data
      - virtuoso_data:/opt/virtuoso-opensource/database/data
      - virtuoso_logs:/opt/virtuoso-opensource/database/logs
    restart: unless-stopped

  ontology-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080" # API port
    environment:
      - ONTOLOGY_FILE=${ONTOLOGY_FILE}
    volumes:
      # Mount the data directory containing ontologies
      - ./data:/app/ontology
    command: python3 /app/api_server.py /app/ontology/${ONTOLOGY_FILENAME:-pizza.owl} # Default to pizza.owl if ONTOLOGY_FILENAME is not set
    depends_on:
      - virtuoso
    restart: unless-stopped

volumes:
  virtuoso_data:
  virtuoso_logs:

